import React, { useEffect, useMemo, useState } from 'react';
import { BookOpen, Search, SlidersHorizontal, UserRound } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import axios from '../../services/axios';
import { apiMessage, asArray, EmptyState, ErrorState, formatMoney, LoadingState } from '../../components/Shared';

export default function CourseCatalog() {
  const location = useLocation(); const detailPath = location.pathname.startsWith('/catalog') ? '/courses' : '/student/courses'; const [courses, setCourses] = useState([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const response = await axios.get('/api/courses'); setCourses(asArray(response.data)); setError(''); } catch (err) { setError(apiMessage(err, 'The catalog could not be loaded.')); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => courses.filter(course => { const text = `${course.title || ''} ${course.description || ''} ${course.instructor?.name || ''}`.toLowerCase(); const matchesQuery = text.includes(query.toLowerCase()); const price = Number(course.price || 0); return matchesQuery && (filter === 'all' || (filter === 'free' ? price === 0 : price > 0)); }), [courses, query, filter]);
  if (loading) return <LoadingState label="Finding courses..." />;
  return <div className="animate-rise" style={{ maxWidth: 1180, margin: '0 auto' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'end', gap: 15, flexWrap: 'wrap', marginBottom: 23 }}><div><div className="eyebrow">Course catalog</div><h1 className="font-display" style={{ margin: '8px 0 7px', fontSize: 'clamp(2rem,4vw,3.2rem)', letterSpacing: '-.06em' }}>Choose something useful.</h1><p className="muted">Practical courses, clear outcomes, room to practice.</p></div><div className="muted" style={{ fontSize: '.84rem' }}>{courses.length} published {courses.length === 1 ? 'course' : 'courses'}</div></div>{error && <div style={{ marginBottom: 18 }}><ErrorState message={error} onRetry={load} /></div>}<div className="surface" style={{ display: 'flex', gap: 10, padding: 12, marginBottom: 20, flexWrap: 'wrap' }}><div style={{ position: 'relative', flex: '1 1 240px' }}><Search size={17} className="muted" style={{ position: 'absolute', left: 12, top: 12 }} /><input className="input" style={{ paddingLeft: 38 }} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by title, topic, or instructor" aria-label="Search courses" /></div><div style={{ position: 'relative', flex: '0 1 170px' }}><SlidersHorizontal size={16} className="muted" style={{ position: 'absolute', left: 12, top: 13 }} /><select className="input" style={{ paddingLeft: 35 }} value={filter} onChange={(e) => setFilter(e.target.value)} aria-label="Filter courses"><option value="all">All prices</option><option value="free">Free courses</option><option value="paid">Paid courses</option></select></div></div>{filtered.length === 0 ? <EmptyState title="No courses match that search." description="Try a broader phrase or clear the price filter." action={<button className="btn btn-secondary btn-sm" type="button" onClick={() => { setQuery(''); setFilter('all'); }}>Clear filters</button>} /> : <div className="course-grid">{filtered.map(course => <Link className="course-card" to={`${detailPath}/${course.id}`} key={course.id}><div className="course-cover">{course.thumbnail_url ? <img src={course.thumbnail_url} alt="" /> : <div className="cover-fallback"><BookOpen size={36} /></div>}<span style={{ position: 'absolute', top: 12, right: 12, padding: '5px 8px', borderRadius: 8, color: 'var(--navy)', background: '#fff', fontSize: '.78rem', fontWeight: 800 }}>{formatMoney(course.price)}</span></div><div className="course-body"><h2 className="course-title">{course.title || 'Untitled course'}</h2><p className="muted" style={{ margin: '10px 0 15px', lineHeight: 1.5, fontSize: '.86rem' }}>{course.description || 'A practical course from the CoursePilot community.'}</p><div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 'auto', color: 'var(--muted)', fontSize: '.8rem' }}><UserRound size={15} /> {course.instructor?.name || 'CoursePilot instructor'}</div></div></Link>)}</div>}</div>;
}