import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, ChevronDown, ChevronRight, PlayCircle } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import axios from '../../services/axios';
import { useAuth } from '../../contexts/AuthContext';
import AuthenticatedHlsPlayer from '../../components/AuthenticatedHlsPlayer';
import { apiMessage, asArray, EmptyState, ErrorState, LoadingState } from '../../components/Shared';

export default function CoursePlayer() {
  const { user } = useAuth();
  const { courseId } = useParams();
  const [course, setCourse] = useState(null); const [active, setActive] = useState(null); const [completed, setCompleted] = useState([]); const [open, setOpen] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [courseResponse, enrollmentResponse] = await Promise.all([axios.get(`/api/courses/${courseId}`), axios.get('/api/student/enrollments')]); const data = courseResponse.data?.data || courseResponse.data; const sections = data.sections || []; const enrollment = asArray(enrollmentResponse.data).find(item => String(item.course_id || item.course?.id || item.id) === String(courseId)); setCourse(data); setCompleted((enrollment?.completed_lesson_ids || []).map(Number)); if (sections[0]) { setOpen({ [sections[0].id]: true }); setActive(sections[0].lessons?.[0] || null); } } catch (err) { setError(apiMessage(err, 'We could not open this course.')); } finally { setLoading(false); } }, [courseId]);
  useEffect(() => { load(); }, [load]);
  const sections = useMemo(() => course?.sections || [], [course]);
  const lessons = useMemo(() => sections.flatMap(section => section.lessons || []), [sections]);
  const progress = lessons.length ? Math.round(completed.filter(id => lessons.some(lesson => Number(lesson.id) === id)).length / lessons.length * 100) : 0;
  const markComplete = async () => { if (!active || completed.includes(Number(active.id))) return; try { await axios.post(`/api/student/lessons/${active.id}/complete`); setCompleted(value => [...value, Number(active.id)]); } catch (err) { setError(apiMessage(err, 'Progress could not be saved.')); } };
  if (loading) return <LoadingState label="Preparing your learning space..." />;
  if (!course) return <div className="app-shell" style={{ padding: 25 }}><ErrorState message={error || 'Course not found.'} onRetry={load} /></div>;
  return <div className="player-page"><header className="player-header"><Link to="/student/dashboard"><ArrowLeft size={17} /> My learning</Link><strong className="font-display">{course.title}</strong><span>{progress}%</span></header><div className="player-layout"><main className="player-main">{active ? <><div className="video-stage">{active.hls_url ? <AuthenticatedHlsPlayer src={active.hls_url} student={user} /> : active.vod_url ? <video controls playsInline src={active.vod_url} style={{ width: '100%', height: '100%' }} /> : <EmptyState title="Video coming soon" description="This lesson has no playable media yet." />}</div><section style={{ padding: 28 }}><div className="eyebrow">Lesson {lessons.findIndex(item => item.id === active.id) + 1}</div><h1 className="font-display">{active.title}</h1><button type="button" className="btn btn-primary" onClick={markComplete} disabled={completed.includes(Number(active.id))}><CheckCircle2 size={17} /> {completed.includes(Number(active.id)) ? 'Completed' : 'Mark complete'}</button></section></> : <EmptyState title="Choose a lesson to begin." description="Select a lesson from the course outline." />}</main><aside className="player-sidebar"><div style={{ padding: 18 }}><div className="eyebrow">Course content</div><h2 className="font-display">{lessons.length} lessons</h2></div>{sections.map((section, index) => <div key={section.id}><button type="button" onClick={() => setOpen(value => ({ ...value, [section.id]: !value[section.id] }))} className="lesson-section">{open[section.id] ? <ChevronDown size={15} /> : <ChevronRight size={15} />} {index + 1}. {section.title}</button>{open[section.id] && (section.lessons || []).map(lesson => <button type="button" key={lesson.id} className={`lesson-item ${active?.id === lesson.id ? 'active' : ''}`} onClick={() => setActive(lesson)}><PlayCircle size={16} />{lesson.title}</button>)}</div>)}</aside></div></div>;
}
