import React, { useState } from 'react';
import { ArrowLeft, BookOpen, DollarSign } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import axios from '../../services/axios';
import { apiMessage, SubmitButton } from '../../components/Shared';

export default function CreateCourse() {
  const navigate = useNavigate(); const [form, setForm] = useState({ title: '', description: '', price: '' }); const [errors, setErrors] = useState({}); const [loading, setLoading] = useState(false);
  const submit = async event => { event.preventDefault(); setLoading(true); setErrors({}); try { const response = await axios.post('/api/courses', { ...form, price: Number(form.price) }); const course = response.data?.data || response.data; navigate(course?.id ? `/instructor/courses/${course.id}/syllabus` : '/instructor/courses'); } catch (err) { setErrors(err.response?.data?.errors || { general: apiMessage(err, 'We could not create this course.') }); } finally { setLoading(false); } };
  const field = (name, value) => setForm(prev => ({ ...prev, [name]: value }));
  return <div className="animate-rise" style={{ maxWidth: 760, margin: '0 auto' }}><Link to="/instructor/courses" className="muted" style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: '.84rem', marginBottom: 18 }}><ArrowLeft size={15} /> Back to courses</Link><div style={{ marginBottom: 22 }}><div className="eyebrow">Instructor studio</div><h1 className="font-display" style={{ margin: '8px 0 7px', fontSize: 'clamp(2rem,4vw,3.2rem)', letterSpacing: '-.06em' }}>Start with the promise.</h1><p className="muted">Give learners a clear reason to show up.</p></div><form onSubmit={submit} className="surface" style={{ padding: 'clamp(21px,4vw,36px)', display: 'grid', gap: 17 }}>{errors.general && <div className="notice notice-error">{errors.general}</div>}<div><label className="label" htmlFor="title">Course title</label><div style={{ position: 'relative' }}><BookOpen size={17} className="muted" style={{ position: 'absolute', left: 13, top: 13 }} /><input id="title" className="input" style={{ paddingLeft: 39 }} required value={form.title} onChange={e => field('title', e.target.value)} placeholder="e.g. Field notes for better product decisions" /></div>{errors.title && <div className="error-text">{errors.title[0]}</div>}</div><div><label className="label" htmlFor="price">Price</label><div style={{ position: 'relative' }}><DollarSign size={17} className="muted" style={{ position: 'absolute', left: 13, top: 13 }} /><input id="price" className="input" style={{ paddingLeft: 39 }} required type="number" min="0" step="0.01" value={form.price} onChange={e => field('price', e.target.value)} placeholder="0.00" /></div>{errors.price && <div className="error-text">{errors.price[0]}</div>}</div><div><label className="label" htmlFor="description">Description</label><textarea id="description" className="input" rows="7" required value={form.description} onChange={e => field('description', e.target.value)} placeholder="What will learners be able to do after completing this course?" />{errors.description && <div className="error-text">{errors.description[0]}</div>}</div><div style={{ display: 'flex', justifyContent: 'end', gap: 9, paddingTop: 10, borderTop: '1px solid var(--line)' }}><button type="button" className="btn btn-secondary" onClick={() => navigate('/instructor/courses')}>Cancel</button><SubmitButton loading={loading} type="submit">Create course</SubmitButton></div></form></div>;
}