import React, { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, CheckCircle2, Clock3, PlusCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import axios from '../../services/axios';
import { apiMessage, asArray, ErrorState, LoadingState } from '../../components/Shared';

export default function Dashboard() {
  const [courses, setCourses] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const response = await axios.get('/api/courses'); setCourses(asArray(response.data)); setError(''); } catch (err) { setError(apiMessage(err, 'We could not load your course studio.')); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  if (loading) return <LoadingState label="Loading your course studio..." />;
  const published = courses.filter(course => ['approved', 'published'].includes(String(course.status || '').toLowerCase())).length;
  return <div className="animate-rise" style={{ maxWidth: 1180, margin: '0 auto' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'end', gap: 15, flexWrap: 'wrap', marginBottom: 28 }}><div><div className="eyebrow">Instructor studio</div><h1 className="font-display" style={{ margin: '8px 0 7px', fontSize: 'clamp(2rem,4vw,3.2rem)', letterSpacing: '-.06em' }}>Make the work teachable.</h1><p className="muted">A clear view of the courses you are shaping.</p></div><Link to="/instructor/courses/create" className="btn btn-primary"><PlusCircle size={16} /> New course</Link></div>{error && <ErrorState message={error} onRetry={load} />}<div className="stat-grid"><div className="stat-card"><BookOpen size={19} style={{ color: 'var(--teal)' }} /><div className="muted" style={{ fontSize: '.8rem', marginTop: 12 }}>Total courses</div><strong className="font-display" style={{ fontSize: '1.8rem' }}>{courses.length}</strong></div><div className="stat-card"><CheckCircle2 size={19} style={{ color: 'var(--teal)' }} /><div className="muted" style={{ fontSize: '.8rem', marginTop: 12 }}>Published</div><strong className="font-display" style={{ fontSize: '1.8rem' }}>{published}</strong></div><div className="stat-card"><Clock3 size={19} style={{ color: 'var(--sun)' }} /><div className="muted" style={{ fontSize: '.8rem', marginTop: 12 }}>In review</div><strong className="font-display" style={{ fontSize: '1.8rem' }}>{courses.filter(course => String(course.status || '').toLowerCase() === 'pending').length}</strong></div><div className="stat-card"><div style={{ color: 'var(--coral)', fontWeight: 800 }}>—</div><div className="muted" style={{ fontSize: '.8rem', marginTop: 12 }}>Learner analytics</div><strong style={{ display: 'block', marginTop: 8, fontSize: '.9rem' }}>Not connected</strong></div></div><div className="surface" style={{ padding: 23, marginTop: 19 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 10 }}><h2 className="font-display" style={{ margin: 0 }}>Recent course work</h2><Link to="/instructor/courses" style={{ color: 'var(--teal)', fontWeight: 700, fontSize: '.85rem' }}>Manage all <ArrowRight size={14} style={{ verticalAlign: 'middle' }} /></Link></div>{courses.length === 0 ? <p className="muted" style={{ margin: '22px 0 0' }}>Create your first course to see it here.</p> : <div style={{ display: 'grid', gap: 10, marginTop: 17 }}>{courses.slice(0, 4).map(course => <div key={course.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 14, padding: '13px 0', borderTop: '1px solid var(--line)' }}><span style={{ fontWeight: 700 }}>{course.title || 'Untitled course'}</span><span className="eyebrow" style={{ letterSpacing: '.08em' }}>{course.status || 'draft'}</span></div>)}</div>}</div></div>;
}